name: flutter_projects
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #state management
  flutter_bloc: ^8.0.1



  equatable: ^2.0.3
  # flutter_icons: ^1.1.0
  #Firebase
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  # firebase_auth: ^3.3.11
  # firebase_core: ^1.13.1
  #Service Locator
  get_it: ^7.2.0

  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  uuid: ^3.0.6
  cached_network_image: ^3.2.0
  #show toast
  # add this line to your dependencies
  fluttertoast: ^8.0.9
  modal_bottom_sheet: ^2.0.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  toast: ^0.3.0
  audioplayers: ^0.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/instagram.png"

flutter:
  uses-material-design: true
  # assets:
    # - assets/
    # - assets/EcommerceAppTarek/
    # - assets/EcommerceAppTarek/
    # - assets/gameImages/
    # - assets/musicAudio/

  
  # fonts:
    # - family: Cairo
      # fonts:
        # - asset: assets/Cairo-Regular.ttf

 