name: app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  geolocator: ^10.1.0
  intl: ^0.19.0
  weather: ^3.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: metropolis
      fonts:
        - asset: assets/fonts/metropolis.extra-light.otf
          weight: 100
        - asset: assets/fonts/metropolis.light.otf
          weight: 300
        - asset: assets/fonts/metropolis.regular.otf
          weight: 400
        - asset: assets/fonts/metropolis.medium.otf
          weight: 500
        - asset: assets/fonts/metropolis.semi-bold.otf
          weight: 600
        - asset: assets/fonts/metropolis.bold.otf
          weight: 700
        - asset: assets/fonts/metropolis.extra-bold.otf
          weight: 800
        - asset: assets/fonts/metropolis.black.otf
          weight: 900

